apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: recommendation
  namespace: default
spec:
  owner:
    projectName: gcp-microservice-demo

  componentType: deployment/service
  autoDeploy: true

  parameters:
    replicas: 1
    port: 8080
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: recommendation
  namespace: default
spec:
  owner:
    componentName: recommendation
    projectName: gcp-microservice-demo
  containers:
    main:
      image: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice:v0.10.3
      env:
        - key: DISABLE_PROFILER
          value: "1"
        - key: PORT
          value: "8080"
        - key: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalog:80"
