apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: checkout
  namespace: default
spec:
  owner:
    projectName: gcp-microservice-demo

  componentType: deployment/service

  parameters:
    replicas: 1
    port: 5050
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: checkout
  namespace: default
spec:
  owner:
    componentName: checkout
    projectName: gcp-microservice-demo
  containers:
    main:
      image: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.3
      env:
        - key: DISABLE_PROFILER
          value: "1"
        - key: PORT
          value: "5050"
        - key: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalog:80"
        - key: SHIPPING_SERVICE_ADDR
          value: "shipping:80"
        - key: PAYMENT_SERVICE_ADDR
          value: "payment:80"
        - key: EMAIL_SERVICE_ADDR
          value: "email:80"
        - key: CURRENCY_SERVICE_ADDR
          value: "currency:80"
        - key: CART_SERVICE_ADDR
          value: "cart:80"


---

apiVersion: openchoreo.dev/v1alpha1
kind: ComponentDeployment
metadata:
  name: checkout-development
  namespace: default
spec:
  owner:
    projectName: gcp-microservice-demo
    componentName: checkout

  environment: development
