apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: redis
  namespace: default
spec:
  owner:
    projectName: gcp-microservice-demo

  componentType: deployment/service

  parameters:
    replicas: 1
    port: 6379
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: redis
  namespace: default
spec:
  owner:
    componentName: redis
    projectName: gcp-microservice-demo
  containers:
    main:
      image: redis:7.2-alpine

---

apiVersion: openchoreo.dev/v1alpha1
kind: ComponentDeployment
metadata:
  name: redis-development
  namespace: default
spec:
  owner:
    projectName: gcp-microservice-demo
    componentName: redis

  environment: development
