apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: shipping
  namespace: default
spec:
  owner:
    projectName: gcp-microservice-demo

  componentType: deployment/service

  parameters:
    replicas: 1
    port: 50055
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: shipping
  namespace: default
spec:
  owner:
    componentName: shipping
    projectName: gcp-microservice-demo
  containers:
    main:
      image: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.3
      env:
        - key: DISABLE_PROFILER
          value: "1"
        - key: PORT
          value: "50055"

---

apiVersion: openchoreo.dev/v1alpha1
kind: ComponentDeployment
metadata:
  name: shipping-development
  namespace: default
spec:
  owner:
    projectName: gcp-microservice-demo
    componentName: shipping

  environment: development
